[package]
name = "vcpmobile-store"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
rusqlite.workspace = true
vcpmobile-domain = { path = "../domain" }
vcpmobile-protocol = { path = "../protocol" }
